name: Publish Nuget

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish Vista.Controllers.ScreenMaster3
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/Vista.Controllers.ScreenMaster3/Vista.Controllers.ScreenMaster3.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}